# Generated by Django 5.2.4 on 2025-07-15 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0002_bookmodel_book_isbn_idx'),
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf', models.CharField(max_length=255)),
                ('qshelf', models.CharField(max_length=255)),
                ('floor', models.CharField(max_length=255)),
                ('room', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('available', 'Disponível'), ('borrowed', 'Emprestado'), ('reserved', 'Reservado'), ('lost', 'Perdido')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_stock_entries', to='book.bookmodel')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_stock_entries', to='branch.branchmodel')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='bookstock_status_idx')],
            },
        ),
    ]
