# Generated by Django 5.2.4 on 2025-07-12 19:41

import django.contrib.postgres.indexes
from django.db import migrations, models
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
        ('book_category', '0001_initial'),
    ]

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('publisher', models.CharField(max_length=255)),
                ('edition', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=100)),
                ('book_type', models.CharField(choices=[('physical', 'Físico'), ('ebook', 'eBook')], max_length=10)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('publication_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(related_name='books', to='author.authormodel')),
                ('categories', models.ManyToManyField(related_name='books', to='book_category.bookcategorymodel')),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['title'], name='book_title_trgm_gin', opclasses=['gin_trgm_ops'])],
            },
        ),
    ]
