# Generated by Django 5.2.4 on 2025-07-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('book', '0001_initial'),
        ('book_category', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bookmodel',
            index=models.Index(fields=['isbn'], name='book_isbn_idx'),
        ),
    ]
